.\" Manpage for innoextract.
.\" Contact daniel@constexpr.org to correct errors or typos.
.TH INNOEXTRACT 1 "2012-03-04" "1.0"
.SH NAME
innoextract \- tool to extract installers created by Inno Setup
.SH SYNOPSIS
.B innoextract
.RB [ -behlLqstv ]
.RB [ -c color ]
.RB [ -p progress ]
.I installers ...
.SH DESCRIPTION
.B innoextract
is a tool that can extract installer executables created by Inno Setup.
.PP
.B innoextract
will extract files from a installers specified on the command line.
.PP
To extract a multi-part installer with external data files, only the executable (.exe) file needs to be given as an argument to
.B innoextract.
.SH OPTIONS
.TP
.B \-c --color [enable]
By default
.B innoextract
will try to detect if the terminal supports shell escape codes and enable or disable color output accordingly. Pass
.B 1
or
.B true
to
.B --color
to force color output. Pass
.B 0
or
.B false
to never output color codes.
.TP
.B --dump
Don't convert Windows paths to UNIX paths and don't substitute variables in paths.
.TP
.B \-e --extract
Extract all files to the current directory. This is the default action. You may only specify one of
.B --extract
,
.B --list
and
.B --test
.TP
.B \-h --help
Show a list of the supported options.
.TP
.B \--license
Show license information.
.TP
.B \-l --list
List files contained in the installer but don't extract anything. You may only specify one of
.B --extract
,
.B --list
and
.B --test
.TP
.B \-L --lowercase
Convert filenames stored in the installer to lower-case before extracting.
.TP
.B \-p --progress [enable]
By default
.B innoextract
will try to detect if the terminal supports shell escape codes and enable or disable progress bar output accordingly. Pass
.B 1
or
.B true
to
.B --progress
to force progress bar output. Pass
.B 0
or
.B false
to never show a progress bar.
.TP
.B \-q --quiet
Less verbose output.
.TP
.B \-s --silent
Don't output anything except errors and warnings.
.TP
.B \-t --test
Test archive integrity but don't write any output files. You may only specify one of
.B --extract
,
.B --list
and
.B --test
.TP
.B \-v --version
Show the
.B innoextract
version number and supported Inno Setup versions.
.SH LIMITATIONS
.B innoextract
currently only supports extracting all the data. There is no support for extracting individual files, components or languages.

Included scripts and checks are not executed.

Data is always extracted to the current directory and the mapping from Inno Setup variables like the application directory to subdirectories is hard-coded.

.B innoextract
does not check if an installer includes multiple files with the same name and will continually overwrite the destination file when extracting.

Names for data files in multi-file installers must follow the standard naming scheme.

Encrypted installers are not supported.
.SH SEE ALSO
cabextract(1), unshield(1)
.SH BUGS
No known bugs.
.SH AUTHOR
Daniel Scharrer (daniel@constexpr.org)
